In [1]:
import pickle

demofile = '/home/anton/Documents/Tulane/Research/ImageNomer/data/anton/cohorts/UKB/demographics.pkl'

demo = pickle.load(open(demofile, 'rb'))

print(demo.keys())

dict_keys(['f_22001_0_0', 'f_21003_3_0', 'f_21003_2_0', 'f_21000_0_0', 'CaAfCarDiff', 'CaIndDiff', 'CaChiDiff', 'f_21000_0_0_comb', 'longitudinal'])

In [2]:
import pandas as pd

prsfile = '/home/anton/Documents/Tulane/Research/Work/UKB/ukb669358.csv'

df = pd.read_csv(prsfile)

df

,eid,22438-0.0,22828-0.0,26201-0.0,26201-0.1,26201-0.2,26201-0.3,26202-0.0,26203-0.0,26204-0.0,...,26280-0.0,26281-0.0,26282-0.0,26283-0.0,26284-0.0,26285-0.0,26286-0.0,26287-0.0,26289-0.0,26290-0.0
0,1000010,24.0,24.0,-8.59448,53.5432,-25.5345,-5.58124,0.090430,NaN,0.454718,...,NaN,NaN,NaN,-1.266990,NaN,-2.418220,NaN,1.396070,0.235631,NaN
1,1000028,24.0,24.0,-8.82721,55.5425,-24.8297,-4.62080,0.532518,NaN,0.744924,...,NaN,NaN,NaN,-1.888840,NaN,-0.732430,NaN,-2.241290,1.342540,NaN
2,1000034,24.0,24.0,-8.11155,55.8063,-25.3930,-4.87957,0.076680,NaN,-0.898174,...,NaN,NaN,NaN,-1.512680,NaN,-0.924251,NaN,0.568084,0.809110,NaN
3,1000045,24.0,24.0,-8.38242,54.2487,-26.7742,-4.59355,-0.464510,NaN,0.641305,...,NaN,NaN,NaN,-0.573551,NaN,1.107590,NaN,-0.831071,1.206220,NaN
4,1000052,24.0,24.0,-9.68984,54.7994,-26.4935,-5.23656,-1.325150,NaN,0.712353,...,NaN,NaN,NaN,-0.965918,NaN,1.336340,NaN,0.183481,-0.667431,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502401,6024847,24.0,24.0,-8.32149,55.7851,-26.1824,-4.42063,0.508821,NaN,-0.301762,...,NaN,NaN,NaN,-2.219450,NaN,-0.735801,NaN,0.549993,1.145850,NaN
502402,6024859,24.0,24.0,-9.70670,53.9284,-24.5449,-6.14250,0.921283,NaN,0.457370,...,NaN,NaN,NaN,-0.224810,NaN,-0.984422,NaN,1.842180,-0.235246,NaN
502403,6024862,24.0,24.0,-8.93189,53.7414,-26.7339,-4.34077,0.229707,-0.098649,1.028010,...,0.823009,1.73155,0.844925,-1.458470,-1.54001,-0.899374,-0.029317,-0.645358,2.077700,2.14566
502404,6024871,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502405,6024885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
from math import isnan

fieldsfile = '/home/anton/Documents/Tulane/Research/Work/UKB/fields.ukb'
fields = []

with open(fieldsfile, 'r') as f:
    for line in f:
        fields.append(f'{int(line)}-0.0')
        
for j,field in enumerate(fields):
    demo[field] = dict()
    nancount = 0
    for i,sub in enumerate(demo['f_21003_2_0']):
        try:
            val = df[df['eid'] == sub][field].array[0]
            if isnan(val):
                nancount += 1
                continue
            demo[field][sub] = val
        except Exception as e:
            pass
        if i % 10000 == 0:
            print(f'Done {i}')
    print(f'{j} {len(demo[field])} {nancount}')

print('Complete')

Done 0
Done 10000
Done 20000
Done 30000
Done 40000
0 39569 1046
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
1 39569 1046
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
2 39520 1095
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
3 39520 1095
Done 30000
4 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
5 39520 1095
Done 30000
6 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
7 39520 1095
Done 30000
8 7496 33119
Done 30000
9 7496 33119
Done 30000
10 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
11 39520 1095
Done 30000
12 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
13 39520 1095
Done 30000
14 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
15 39520 1095
Done 30000
16 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
17 39520 1095
Done 30000
18 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
19 39520 1095
Done 30000
20 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
21 39520 1095
Done 30000
22 7496 33119
Done 30000
23 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
24 39520 1095
Done 30000
25 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
26 39520 1095
Done 30000
27 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
28 39520 1095
Done 30000
29 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
30 39520 1095
Done 30000
31 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
32 39520 1095
Done 30000
33 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
34 39520 1095
Done 30000
35 7496 33119
Done 30000
36 7496 33119
Done 30000
37 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
38 39520 1095
Done 30000
39 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
40 39520 1095
Done 30000
41 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
42 39520 1095
Done 30000
43 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
44 39520 1095
Done 30000
45 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
46 39520 1095
Done 30000
47 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
48 39520 1095
Done 30000
49 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
50 39520 1095
Done 30000
51 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
52 39520 1095
Done 30000
53 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
54 39520 1095
Done 30000
55 7496 33119
Done 30000
56 7496 33119
Done 30000
57 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
58 39520 1095
Done 30000
59 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
60 39520 1095
Done 30000
61 7496 33119
Done 30000
62 7496 33119
Done 30000
63 7496 33119
Done 30000
64 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
65 39520 1095
Done 30000
66 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
67 39520 1095
Done 30000
68 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
69 39520 1095
Done 30000
70 7496 33119
Done 30000
71 7496 33119
Done 30000
72 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
73 39520 1095
Done 30000
74 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
75 39520 1095
Done 30000
76 7496 33119
Done 30000
77 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
78 39520 1095
Done 30000
79 7496 33119
Done 30000
80 7496 33119
Done 30000
81 7496 33119
Done 30000
82 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
83 39520 1095
Done 30000
84 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
85 39520 1095
Done 30000
86 7496 33119
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
87 39520 1095
Done 0
Done 10000
Done 20000
Done 30000
Done 40000
88 39520 1095
Done 30000
89 7496 33119
Complete

In [25]:
# Write new demo

pickle.dump(demo, open(demofile, 'wb'))

print('Complete')

Complete